export enum  StatusEnum{
    ASSIGN_TO_APPROVAL = 'ASSIGN TO APPROVAL',
    SENT_FOR_APPROVAL = 'SENT FOR APPROVAL',
    CANCELED = 'CANCELED',
    REJECTED = 'REJECTED',
    READY_TO_RECEIVED = 'READY TO RECEIVED',
    RECEIVED ='RECEIVED',
    READY_TO_RETURN = 'READY TO RETURN',
    RETURNED ='RETURNED',
    NOT_RETURNED = 'NOT RETURNED',
    CLOSED = 'CLOSED'
}